### PR TITLE
Secure Sampling for OM and ROM

### LINKED ISSUE #55: Optimized's infinite loop
The current `Optimized._sample_ranking` samples rankings until the number of sampled rankings becomes `sample_num`.
However, this sometimes never ends: the number of possible rankings can be less than `sample_num`.

So it must be "until rankings are sampled `sample_num` times", not "until the number of sampled rankings reaches `sample_num`".

### PR DESCRIPTION
**Pull request by tmanabe**
Closes #55 .

### CODE REVIEW

**Comment by tmanabe** [comment]
CircleCI is not working? It looks that this PR failed to pass some test cases.

**Comment by mpkato** [comment]
I guess they upgrade the version and accept only .circleci/config.yml .

**Comment by tmanabe** [comment]
I set up #59 .

Could you test and review this PR in your local environment?
In my environment, this PR passed all the test cases (of course).

**Comment by mpkato** [comment]
It seems that there are something wrong with `Optimized`. I got the following errors in the test:

```
tests/test_balanced.py::TestBalanced::test_raise_value_error PASSED                                                                          [  1%]
tests/test_balanced.py::TestBalanced::test_interleave PASSED                                                                                 [  3%]
tests/test_balanced.py::TestBalanced::test_init_sampling PASSED                                                                              [  4%]
tests/test_balanced.py::TestBalanced::test_dump PASSED                                                                                       [  6%]
tests/test_balanced.py::TestBalanced::test_evaluate PASSED                                                                                   [  8%]
tests/test_optimized.py::TestOptimized::test_raise_value_error PASSED                                                                        [  9%]
tests/test_optimized.py::TestOptimized::test_init_sampling FAILED                                                                            [ 11%]
tests/test_optimized.py::TestOptimized::test_dump FAILED                                                                                     [ 13%]
tests/test_optimized.py::TestOptimized::test__unbiasedness_constraints PASSED                                                                [ 14%]
tests/test_optimized.py::TestOptimized::test__sensitivity FAILED                                                                             [ 16%]
tests/test_optimized.py::TestOptimized::test__compute_probabilities FAILED                                                                   [ 18%]
tests/test_optimized.py::TestOptimized::test_interleave FAILED                                                                               [ 19%]
tests/test_optimized.py::TestOptimized::test_evaluate FAILED                                                                                 [ 21%]
tests/test_probabilistic.py::TestProbabilistic::test_score_interleave PASSED                                                                 [ 22%]
tests/test_probabilistic.py::TestProbabilistic::test_evaluate_interleave PASSED                                                              [ 24%]
tests/test_probabilistic.py::TestProbabilistic::test_score_multileave PASSED                                                                 [ 26%]
tests/test_probabilistic.py::TestProbabilistic::test_evaluate_multileave PASSED                                                              [ 27%]
tests/test_probabilistic.py::TestProbabilistic::test_init_sampling PASSED                                                                    [ 29%]
tests/test_probabilistic.py::TestProbabilistic::test_dump PASSED                                                                             [ 31%]
tests/test_probabilistic_interleave.py::TestProbabilisticInterleave::test_sanity PASSED                                                      [ 32%]
tests/test_probabilistic_interleave.py::TestProbabilisticInterleave::test_uniform PASSED                                                     [ 34%]
tests/test_probabilistic_interleave.py::TestProbabilisticInterleave::test_ranking_with_teams PASSED                                          [ 36%]
tests/test_probabilistic_interleave.py::TestProbabilisticInterleave::test_memorylessness PASSED                                              [ 37%]
tests/test_probabilistic_interleave.py::TestProbabilisticInterleave::test_softmax PASSED                                                     [ 39%]
tests/test_probabilistic_interleave.py::TestProbabilisticInterleave::test_interaction PASSED                                                 [ 40%]
tests/test_probabilistic_interleave.py::TestProbabilisticInterleave::test_uniqueness PASSED                                                  [ 42%]
tests/test_probabilistic_interleave.py::TestProbabilisticInterleave::test_no_shortage PASSED                                                 [ 44%]
tests/test_probabilistic_interleave_speed.py::TestProbabilisticInterleaveSpeed::test_interleave PASSED                                       [ 45%]
tests/test_probabilistic_multileave.py::TestProbabilisticMultileave::test_sanity PASSED                                                      [ 47%]
tests/test_probabilistic_multileave.py::TestProbabilisticMultileave::test_uniform PASSED                                                     [ 49%]
tests/test_probabilistic_multileave.py::TestProbabilisticMultileave::test_round_robin PASSED                                                 [ 50%]
tests/test_probabilistic_multileave.py::TestProbabilisticMultileave::test_softmax PASSED                                                     [ 52%]
tests/test_probabilistic_multileave.py::TestProbabilisticMultileave::test_interaction PASSED                                                 [ 54%]
tests/test_probabilistic_multileave.py::TestProbabilisticMultileave::test_uniqueness PASSED                                                  [ 55%]
tests/test_probabilistic_multileave.py::TestProbabilisticMultileave::test_no_shortage PASSED                                                 [ 57%]
tests/test_roughly_optimized.py::TestOptimized::test_raise_value_error <- tests/test_optimized.py PASSED                                     [ 59%]
tests/test_roughly_optimized.py::TestOptimized::test_init_sampling <- tests/test_optimized.py FAILED                                         [ 60%]
tests/test_roughly_optimized.py::TestOptimized::test_dump <- tests/test_optimized.py FAILED                                                  [ 62%]
tests/test_roughly_optimized.py::TestOptimized::test__unbiasedness_constraints <- tests/test_optimized.py PASSED                             [ 63%]
tests/test_roughly_optimized.py::TestOptimized::test__sensitivity <- tests/test_optimized.py PASSED                                          [ 65%]
tests/test_roughly_optimized.py::TestOptimized::test__compute_probabilities <- tests/test_optimized.py FAILED                                [ 67%]
tests/test_roughly_optimized.py::TestOptimized::test_interleave <- tests/test_optimized.py FAILED                                            [ 68%]
tests/test_roughly_optimized.py::TestOptimized::test_evaluate <- tests/test_optimized.py FAILED                                              [ 70%]
tests/test_roughly_optimized.py::TestRoughlyOptimized::test_raise_value_error <- tests/test_optimized.py PASSED                              [ 72%]
tests/test_roughly_optimized.py::TestRoughlyOptimized::test_init_sampling <- tests/test_optimized.py FAILED                                  [ 73%]
tests/test_roughly_optimized.py::TestRoughlyOptimized::test_dump <- tests/test_optimized.py PASSED                                           [ 75%]
tests/test_roughly_optimized.py::TestRoughlyOptimized::test__unbiasedness_constraints <- tests/test_optimized.py PASSED                      [ 77%]
tests/test_roughly_optimized.py::TestRoughlyOptimized::test__sensitivity <- tests/test_optimized.py PASSED                                   [ 78%]
tests/test_roughly_optimized.py::TestRoughlyOptimized::test__compute_probabilities <- tests/test_optimized.py PASSED                         [ 80%]
tests/test_roughly_optimized.py::TestRoughlyOptimized::test_interleave <- tests/test_optimized.py FAILED                                     [ 81%]
tests/test_roughly_optimized.py::TestRoughlyOptimized::test_evaluate <- tests/test_optimized.py PASSED                                       [ 83%]
tests/test_roughly_optimized.py::TestRoughlyOptimized::test__compute_probabilities_fail FAILED                                               [ 85%]
tests/test_roughly_optimized.py::TestRoughlyOptimized::test__compute_probabilities_loosely PASSED                                            [ 86%]
tests/test_simulation.py::TestSimulation::test_simulator_evaluate PASSED                                                                     [ 88%]
tests/test_simulation.py::TestSimulation::test_simulator_ndcg PASSED                                                                         [ 90%]
tests/test_simulation.py::TestSimulation::test_measure_error PASSED                                                                          [ 91%]
tests/test_team_draft.py::TestTeamDraft::test_interleave PASSED                                                                              [ 93%]
tests/test_team_draft.py::TestTeamDraft::test_team_draft_ranking PASSED                                                                      [ 95%]
tests/test_team_draft.py::TestTeamDraft::test_dump PASSED                                                                                    [ 96%]
tests/test_team_draft.py::TestTeamDraft::test_multileave PASSED                                                                              [ 98%]
tests/test_team_draft.py::TestTeamDraft::test_evaluate PASSED                                                                                [100%]
```

**Comment by mpkato** [comment]
Some tests raised `ValueError: Optimization failed`,
while the other test cases failed due to the mismatch between actual and expected outputs.

Test cases are passed in `feature/57`.

**Comment by tmanabe** [comment]
Hmm

**Comment by mpkato** [comment]
Sorry, this is probably my mistake ... wait a moment

**Comment by mpkato** [comment]
Again, sorry for confusion. It looks fine now.

**Comment by tmanabe** [comment]
Thanks a lot!

**Pull request merged**
